Repository jungeebah/herekochu, pull requests merged in 2020-05, with the labels that each got.

#12 Adding Kabhi Khusi Kabhi Gum to the List
  _posts/2020-05-16-Kabhi Khushi Kabhie Gham.md
  assets/images/K3G2001.jpg
Labels: enhancement

#22 Fixed K3G Title
  _posts/2020-05-16-Kabhi Khushi Kabhie Gham.md
Labels: bug

#31 Website added
  .gitignore
  _config.yml
Labels: feature

#34 Added Kabaddi movie
  _posts/2020-05-03-Rashomon.markdown
  _posts/2020-05-04-Dunkirk.markdown
  _posts/2020-05-06-Parasite.markdown
  _posts/2020-05-13-Sholay.md
  _posts/2020-05-19-Kabaddi.md
  _posts/2020-05-19-Tumbbad.md
  assets/images/K3G2001.jpg
  assets/images/Kabaddi.jpg
  assets/images/Rashomon.jpg
  assets/images/Tumbbad.jpg
  assets/images/badlapur.jpg
  assets/images/dunkirk.jpg
  assets/images/ishq1997.jpg
  assets/images/parasite.jpg
  assets/images/rambolastblood.jpg
  assets/images/rashmon.jpg
  assets/images/sholay.jpg
Labels: feature

#32 Picture Reformatted
  _posts/2020-05-03-Rashomon.markdown
  _posts/2020-05-04-Dunkirk.markdown
  _posts/2020-05-06-Parasite.markdown
  _posts/2020-05-13-Sholay.md
  assets/images/K3G2001.jpg
  assets/images/Rashomon.jpg
  assets/images/badlapur.jpg
  assets/images/dunkirk.jpg
  assets/images/ishq1997.jpg
  assets/images/parasite.jpg
  assets/images/rambolastblood.jpg
  assets/images/rashmon.jpg
  assets/images/sholay.jpg
Labels: enhancement

#37 Adding Chennai Express and reformatting picture pixels
  _posts/2020-05-19-Kabaddi.md
  _posts/2020-05-20-ChennaiExpress.md
  assets/images/ChennaiExpress.jpg
  assets/images/K3G2001.jpg
  assets/images/Kabaddi.jpg
  assets/images/Tumbbad.jpg
  assets/images/badlapur.jpg
  assets/images/dunkirk.jpg
  assets/images/ishq1997.jpg
  assets/images/rambolastblood.jpg
  assets/images/sholay.jpg
Labels: feature

#49 Edited _Confi.yml file
  _config.yml
Labels: enhancement

#63 fixed subscription for daamireview
  _config.yml
  _includes/subscribe-form.html
Labels: bug

#64 Mergify: configuration update
  .mergify.yml
Labels: enhancement
