Repository jungeebah/herekochu, pull requests merged in 2020-06, with the labels that each got.

#73 added working tasks
  README.md
Labels: question

#74 Adhikari deepak about page
  _includes/navigation.html
  _layouts/about.html
  about.html
  assets/images/ArjunGharti.jpg
  assets/images/BijendraBasnet.jpg
  assets/images/BiwashShrestha.jpg
  assets/images/BuddhiJungGurung.jpg
  assets/images/DeepakAdhikari.jpg
  assets/images/RoshanPariyar.jpg
  style-guide.html
Labels: Weekly Review, feature

#83 Added 5 movies
  _posts/2020-05-03-Rashomon.markdown
  _posts/2020-05-16-Badlapur.md
  _posts/2020-05-16-Kabhi Khushi Kabhie Gham.md
  _posts/2020-05-16-RamboLastBlood.md
  _posts/2020-05-20-ChennaiExpress.md
  _posts/2020-06-14-Drishyam.md
  _posts/2020-06-14-Gulabo Sitabo.md
  _posts/2020-06-14-Jolly LLB.md
  _posts/2020-06-14-JollyLLB2.md
  _posts/2020-06-14-Sanju.md
  assets/images/Drishyam.jpg
  assets/images/GulaboSitabo.jpg
  assets/images/JollyLLB.jpg
  assets/images/JollyLLB2.jpg
  assets/images/Sanju.jpg
  assets/images/draft_one.pdf
Labels: feature

#84 Updated Ipad's Padding Large Screem
  _assets/scss/components/_about.scss
  _data/members.yml
  about.html
  assets/css/app.min.css
Labels: bug

#87 Update display
  .eslintrc
  Procfile
  _assets/scss/app.scss
  _assets/scss/components/_language.scss
  _assets/scss/components/_post.scss
  _assets/scss/components/_posts.scss
  _data/color.yml
  _includes/navigation.html
  _includes/post-card.html
  _layouts/post.html
  _posts/2020-05-03-Rashomon.markdown
  _posts/2020-05-04-Dunkirk.markdown
  _posts/2020-05-06-Parasite.markdown
  _posts/2020-05-13-Sholay.md
  _posts/2020-05-14-Ishq-1997.md
  _posts/2020-05-16-Badlapur.md
  _posts/2020-05-16-Kabhi Khushi Kabhie Gham.md
  _posts/2020-05-16-RamboLastBlood.md
  _posts/2020-05-19-Kabaddi.md
  _posts/2020-05-19-Tumbbad.md
  _posts/2020-05-20-ChennaiExpress.md
  _posts/2020-06-14-Drishyam.md
  _posts/2020-06-14-Gulabo Sitabo.md
  _posts/2020-06-14-Jolly LLB.md
  _posts/2020-06-14-JollyLLB2.md
  _posts/2020-06-14-Sanju.md
  assets/css/app.min.css
  assets/images/ChennaiExpress.jpg
  assets/images/Drishyam.jpg
  assets/images/GulaboSitabo.jpg
  assets/images/JollyLLB.jpg
  assets/images/JollyLLB2.jpg
  assets/images/K3G2001.jpg
  assets/images/Kabaddi.jpg
  assets/images/Rashomon.jpg
  assets/images/Sanju.jpg
  assets/images/Tumbbad.jpg
  assets/images/badlapur.jpg
  assets/images/drishyam1.jpg
  assets/images/dunkirk.jpg
  assets/images/ishq1997.jpg
  assets/images/parasite.jpg
  assets/images/rambolastblood.jpg
  assets/images/sanju1.jpg
  assets/images/sholay.jpg
  genre.html
  gulpfile.js
  language.html
  nepali.html
  package-lock.json
  package.json
  style-guide.html
Labels: Display, Epic, code, configuration change, necessary

#88 fixed about
  _assets/scss/app.scss
  _assets/scss/components/_posts.scss
  assets/css/app.min.css
Labels: Display

#93 Updated author in JLLB2
  _posts/2020-06-14-JollyLLB2.md
Labels: bug

#94 Added dhulo movie
  _posts/2020-05-19-Tumbbad.md
  _posts/2020-06-14-Sanju.md
  _posts/2020-06-20-Dhulo.md
  assets/images/Dhulo.jpg
Labels: New Review

#96 Hommeage au nepal
  _posts/2020-06-20-Dhulo.md
  _posts/2020-06-20-Hommage au Népal.md
  assets/images/HommageAuNepal.jpg
Labels: New Review

#95 Update 2020-06-20-Dhulo.md
  _posts/2020-06-20-Dhulo.md
Labels: bug
